In [1]:
#Import Data

import pandas as pd
import matplotlib.pyplot as plt

econ_freedom = pd.read_csv("economic_freedom_index2019_data.csv",encoding='latin-1', index_col = "Country")
gender_development = pd.read_csv("gender_development.csv",index_col = "Country")
gender_inequality = pd.read_csv("gender_inequality.csv",index_col = "Country")
historical_index = pd.read_csv("historical_index.csv",index_col = "Country")
human_development = pd.read_csv("human_development.csv",index_col = "Country")
inequality = pd.read_csv("inequality_adjusted.csv",index_col = "Country")
poverty = pd.read_csv("multidimensional_poverty.csv",index_col = "Country")

In [2]:
#Reconcile country names 

def UpdateCountry(df, old, new):
    df.loc[new] = historical_index.loc[old].values
    df = df.drop(old)
    return df

historical_index = UpdateCountry(historical_index,"Hong Kong, China (SAR)","Hong Kong SAR")
historical_index = UpdateCountry(historical_index,"Viet Nam","Vietnam")
historical_index = UpdateCountry(historical_index,"Congo","Congo, Democratic Republic of the Congo")
historical_index = UpdateCountry(historical_index,"Kyrgyzstan","Kyrgyz Republic")
historical_index = UpdateCountry(historical_index,"Lao People's Democratic Republic","Lao P.D.R.")
historical_index = UpdateCountry(historical_index,"Moldova (Republic of)","Moldova")
historical_index = UpdateCountry(historical_index,"Russian Federation","Russia")
historical_index = UpdateCountry(historical_index,"Slovakia","Slovak Republic")
historical_index = UpdateCountry(historical_index,"Tanzania (United Republic of)","Tanzania")
historical_index = UpdateCountry(historical_index,"Venezuela (Bolivarian Republic of)","Venezuela") 
historical_index = UpdateCountry(historical_index,"Bolivia (Plurinational State of)","Bolivia")

,HDI Rank,Human Development Index (1990),Human Development Index (2000),Human Development Index (2010),Human Development Index (2011),Human Development Index (2012),Human Development Index (2013),Human Development Index (2014)
Country,,,,,,,,
Norway,1.0,0.849,0.917,0.940,0.941,0.942,0.942,0.944
Australia,2.0,0.865,0.898,0.927,0.930,0.932,0.933,0.935
Switzerland,3.0,0.831,0.888,0.924,0.925,0.927,0.928,0.930
Denmark,4.0,0.799,0.862,0.908,0.920,0.921,0.923,0.923
Netherlands,5.0,0.829,0.877,0.909,0.919,0.920,0.920,0.922
...,...,...,...,...,...,...,...,...
Russia,50.0,0.729,0.717,0.783,0.790,0.795,0.797,0.798
Slovak Republic,35.0,0.738,0.763,0.827,0.832,0.836,0.839,0.844
Tanzania,151.0,0.369,0.392,0.500,0.506,0.510,0.516,0.521
Venezuela,71.0,0.635,0.673,0.757,0.761,0.764,0.764,0.762
Bolivia,119.0,0.536,0.603,0.641,0.647,0.654,0.658,0.662